// POSTS
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";
export const INCREASE_VOTE = "INCREASE_POST_VOTE";
export const DECREASE_VOTE = "DECREASE_POST_VOTE";
export const INCREASE_COMMENT_COUNT = "INCREASE_COMMENT_COUNT";
export const DECREASE_COMMENT_COUNT = "DECREASE_COMMENT_COUNT";
export const CREATE_POST = "CREATE_POST";
export const RECEIVE_POSTS = "RECEIVE_POSTS";
export const RECEIVE_CATEGORIES = "RECEIVE_CATEGORIES";
export const FILTER_POSTS_BY_CATEGORY = "FILTER_POSTS_BY_CATEGORY";


export const RECEIVE_USER_DATA = "RECEIVE_USER_DATA";



// COMMENTS

export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const ADD_COMMENT = "ADD_COMMENT";
export const RECEIVE_COMMENTS = "RECEIVE_COMMENTS";
export const INCREASE_COMMENT_VOTE_SCORE = "INCREASE_COMMENT_VOTE_SCORE";
export const DECREASE_COMMENT_VOTE_SCORE = "DECREASE_COMMENT_VOTE_SCORE";
export const REMOVE_COMMENT = "REMOVE_COMMENT";





